### ISSUE TITLE
보고서 작성하기

### ISSUE THREAD

**Issue by SuFl3770** [SuFl3770/ToDoList#2]
아tlqkf 플젝 반 유기했는데

**Comment by SuFl3770** [comment]
6월 10일까지 해야 하는데

**Comment by nulta** [comment]
> 6월 10일까지 해야 하는데

저런... 잊으실 수도 있으니 6월 11일에 알려드리겠습니다

**Comment by SuFl3770** [comment]
> > 6월 10일까지 해야 하는데
> 
> 저런... 잊으실 수도 있으니 6월 11일에 알려드리겠습니다

나가

**Comment by Astro-CQM** [comment]
그러면 6월 10일 23시 59분에 알려드리겠습니다

**Comment by SuFl3770** [comment]
> 그러면 6월 10일 23시 59분에 알려드리겠습니다

돌겠네

**Comment by Hoto-Cocoa** [comment]
보고서쓰세요

**Comment by SuFl3770** [comment]
오늘 밤 큰 결심 할 예정

**Comment by Astro-CQM** [comment]
> 오늘 밤 큰 결심 할 예정

래더! 손 놓으면 저 진짜 큰 결심해요~

**Comment by Hoto-Cocoa** [comment]
> 오늘 밤 큰 결심 할 예정

드디어 #7 해결을

**Comment by Astro-CQM** [comment]
> > 오늘 밤 큰 결심 할 예정
> 
> 드디어 #7 해결을

+) #8

**Comment by SuFl3770** [comment]
아이미친 왜 그걸 핑찍어

**Comment by yupi97** [comment]
슈플님 어서 큰 결심 부탁드립니다.

**Comment by nulta** [comment]
*써야 할 보고서 이(가) 당신을 빤히 주시합니다.*

**Comment by SuFl3770** [comment]
아 맞다 미친

**Comment by Astro-CQM** [comment]
보고서작성해슴안해슴?

**Comment by SuFl3770** [comment]
어찌어찌 완료
