### ISSUE TITLE
서버 컴퓨터 교체

### ISSUE THREAD

**Issue by SuFl3770** [SuFl3770/ToDoList#3]
~~Windows 11 -> Ubuntu 22.04 LTS~~

- [ ] ~~디스크 전체 백업~~
- [ ] ~~우분투 설치 미디어 만들기~~
- [ ] ~~갈아엎기~~
- [ ] ~~셋팅하기~~
- [ ] ~~서버 재가동~~

**Comment by Hoto-Cocoa** [comment]
제발 Hypervisor를 쓰십쇼 Hyper-V Server와 ESXi(이제아님) 그리고 Proxmox라는 무료 솔루션이 있다고

**Comment by SuFl3770** [comment]
> 제발 Hypervisor를 쓰십쇼 Hyper-V Server와 ESXi(이제아님) 그리고 Proxmox라는 무료 솔루션이 있다고

그럴가

**Comment by SuFl3770** [comment]
계획변경

서버 컴퓨터 교체 예정
현 : intel N100
예정 : Ryzen 7 7840HS 또는 6000번대 H 프로세서 등

교체에 맞춰 Proxmox(유력) 또는 ESXi 구축 고려 중
기존 서버컴 처분안은 고려중 (전파법 때문에 올해 4분기까진 팔지 못함)
여력이 된다면 클플 네트워크(WAF, CDN, DDoS) 까지 붙일까 생각 중

**Comment by SuFl3770** [comment]
솔직히 이게 맞나 싶긴 한데 주변에 지식 엄청 많은 천재분들이 많으니 상관 없을듯

**Comment by SuFl3770** [comment]
![image](https://github.com/SuFl3770/ToDoList/assets/51531885/a6d396ec-723b-4017-aa56-7847055c081c)
참고용

**Comment by SuFl3770** [comment]
Update. 서버랑 모뎀이랑 같은 곳에 두니까 모뎀이 사망하시는 관계로 내부망 새로 짜야할듯
공유기 사야함

**Comment by SuFl3770** [comment]
주문완료
![image](https://github.com/user-attachments/assets/757b8e8a-527a-4d40-9b60-a79190fc7cc5)

추가 주문할 거

- [x] LPDDR5 SDRAM 주문 (16+16)
- [x] SSD 주문 (1TB?)
- [x] 공유기 주문 (wifi 6 이상겸)

![image](https://github.com/user-attachments/assets/44c187d5-b9d7-4f33-aa37-81578a7a3af2)

구형 Zen 3+ 기반이라 기대만큼은 성능 향상은 없겠다만 여유 자원은 꽤 늘어날거라 예상

**Comment by SuFl3770** [comment]
![image](https://github.com/user-attachments/assets/3e35bb9b-89b4-4472-97c5-1c58055e6a39)
내가 해냄
