### ISSUE TITLE
일본 다녀오기

### ISSUE THREAD

**Issue by SuFl3770** [SuFl3770/ToDoList#4]
온게키 해야함

**Comment by Hoto-Cocoa** [comment]
온게키는 SUMMER가 진짜지 https://www.youtube.com/watch?v=4tq2RcVZ3QY

**Comment by SuFl3770** [comment]
![20241217_160627](https://github.com/user-attachments/assets/7eef711b-f7a5-415f-91c8-897e4f64c8a1)
하고옴
