### ISSUE TITLE
개인 인스턴스 세우기

### ISSUE THREAD

**Issue by SuFl3770** [SuFl3770/ToDoList#5]
본계정 옮길 생각은 아님

**Comment by SuFl3770** [comment]
연다면 호토모에 포크 긴빠이 칠거임

**Comment by Hoto-Cocoa** [comment]
> 연다면 호토모에 포크 긴빠이 칠거임

?

**Comment by SuFl3770** [comment]
일단 서버부터 발품 팔아보자

**Comment by SuFl3770** [comment]
귀찮음
폐기

**Comment by Hoto-Cocoa** [comment]
뭐임 왜 때려침

**Comment by Hoto-Cocoa** [comment]
안된다

**Comment by SuFl3770** [comment]
> 뭐임 왜 때려침

사유
1. 이슈 올릴 땐 자금 여유 괜찮았는데 지금은 조금 빡빡해짐
2. 네트워크와 리눅스를 모르는 내가 잘 관리 할 수 있을지 의문
3. 연다해도 기능에 대한 불만(?)이 있을게 뻔한데 이걸 직접 개발할 자신이 없음
4. (제일 큼) 남이 열어주는 인스턴스가 있음

**Comment by SuFl3770** [comment]
+ #3 에 맞춰 다시 진행될 가능성 있음
